<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-08T22:45:12 GMT+01:00" name="Default suite" finished-at="2024-03-08T22:45:16 GMT+01:00" duration-ms="4033">
    <groups>
    </groups>
    <test started-at="2024-03-08T22:45:12 GMT+01:00" name="Default test" finished-at="2024-03-08T22:45:16 GMT+01:00" duration-ms="4033">
      <class name="DossierTest.TestConnecting">
        <test-method is-config="true" signature="setup()[pri:0, instance:DossierTest.TestConnecting@f58853c]" started-at="2024-03-08T22:44:46 GMT+01:00" name="setup" finished-at="2024-03-08T22:45:10 GMT+01:00" duration-ms="24048" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Connect()[pri:0, instance:DossierTest.TestConnecting@f58853c]" started-at="2024-03-08T22:45:12 GMT+01:00" name="Connect" finished-at="2024-03-08T22:45:14 GMT+01:00" duration-ms="2617" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [rgba(92, 184, 92, 0)] but found [rgba(0, 0, 0, 0)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [rgba(92, 184, 92, 0)] but found [rgba(0, 0, 0, 0)]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at DossierTest.TestConnecting.Connect(TestConnecting.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Connect -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:DossierTest.TestConnecting@f58853c]" started-at="2024-03-08T22:45:15 GMT+01:00" name="tearDown" finished-at="2024-03-08T22:45:15 GMT+01:00" duration-ms="49" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Connect status=FAILURE method=TestConnecting.Connect()[pri:0, instance:DossierTest.TestConnecting@f58853c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="Quit()[pri:0, instance:DossierTest.TestConnecting@f58853c]" started-at="2024-03-08T22:45:16 GMT+01:00" name="Quit" finished-at="2024-03-08T22:45:18 GMT+01:00" duration-ms="1281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quit -->
      </class> <!-- DossierTest.TestConnecting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
